[package]
name = "semval"
description = "Semantic validation"
keywords = ["semantic", "validation"]
version = "0.0.7"
license = "Apache-2.0 OR MIT"
readme = "README.md"
authors = ["Uwe Klotz <uwe.klotz@gmail.com>", "slowtec GmbH <post@slowtec.de>"]
repository = "https://github.com/slowtec/semval"
edition = "2018"

[dependencies]
smallvec = "^0.6"

[features]
default = ["std"]
std = []
