[package]
name = "semval"
description = "Semantic validation"
keywords = ["semantic", "validation"]
version = "0.1.2"
license = "Apache-2.0 OR MIT"
readme = "README.md"
authors = ["slowtec GmbH <post@slowtec.de>", "Uwe Klotz <uwe.klotz@gmail.com>"]
repository = "https://github.com/slowtec/semval"
categories = ["no-std", "rust-patterns"]
edition = "2018"

[dependencies]
smallvec = "^0.6"

[features]
default = ["std"]
std = []
